source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'

def common_pods
  pod 'IdVerification365id'
end

target 'SampleApp-swift' do
  use_frameworks!
  common_pods
end

target 'SampleApp-objc' do
  use_frameworks!
  common_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # Work around to fix the compile error for Xcode 15.1 beta 3
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
    
    if ['Pods-SampleApp-objc'].include? target.name
      target.build_configurations.each do |config|
          config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
          config.build_settings['EMBEDDED_CONTENT_CONTAINS_SWIFT'] = ''
      end
    end
    if ['iProov'].include? target.name
      target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
    if ['iProov'].include? target.name
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
