source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'

def common_pods
  pod 'IdVerification365id'
end

target 'SampleApp-swift' do
  use_frameworks!
  common_pods
end

target 'SampleApp-objc' do
  use_frameworks!
  common_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Pods-SampleApp-objc'].include? target.name
      target.build_configurations.each do |config|
          config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
          config.build_settings['EMBEDDED_CONTENT_CONTAINS_SWIFT'] = ''
      end
    end
    if ['iProov', 'Starscream'].include? target.name
      target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
    if ['Sentry', 'iProov', 'Starscream'].include? target.name
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
    if ['Starscream'].include? target.name
      target.build_configurations.each do |config|
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
          config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
      end
    end
  end
end
